class PolyData:
    pass

class Plotter:
    camera_position: object
    def __init__(
        self, off_screen: bool = ..., window_size: tuple[int, int] | None = ...
    ) -> None: ...
    def set_background(self, color: str) -> None: ...
    def add_mesh(
        self,
        mesh: object,
        color: str = ...,
        show_edges: bool = ...,
        opacity: float = ...,
    ) -> None: ...
    def show(self, screenshot: str | None = ..., auto_close: bool = ...) -> None: ...
    def screenshot(
        self, filename: str | None = ..., return_img: bool = ...
    ) -> object: ...
    def close(self) -> None: ...

def read(path: str) -> object: ...
