from collections.abc import Sequence

class BoundingBox:
    xlen: float
    ylen: float
    zlen: float
    center: Vector

class Vector:
    x: float
    y: float
    z: float
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...

class Shape:
    def exportStep(self, path: str, opt: dict[str, object] | None = ...) -> None: ...
    def exportStl(
        self,
        path: str,
        tolerance: float = ...,
        angularTolerance: float = ...,
    ) -> None: ...
    def BoundingBox(self) -> BoundingBox: ...
    def Volume(self) -> float: ...
    def Solids(self) -> Sequence[Shape]: ...
    def isNull(self) -> bool: ...

class Workplane:
    def box(self, x: float, y: float, z: float) -> Workplane: ...
    def circle(self, radius: float) -> Workplane: ...
    def rect(self, x: float, y: float) -> Workplane: ...
    def extrude(self, amount: float) -> Workplane: ...
    def union(self, other: Workplane) -> Workplane: ...
    def center(self, x: float, y: float) -> Workplane: ...
    def cylinder(self, height: float, radius: float) -> Workplane: ...
    def faces(self, selector: str) -> Workplane: ...
    def workplane(self) -> Workplane: ...
    def hole(self, diameter: float) -> Workplane: ...
    def translate(self, vector: tuple[float, float, float]) -> Workplane: ...
    def rotate(
        self,
        startVector: tuple[float, float, float],
        endVector: tuple[float, float, float],
        angleDegrees: float,
    ) -> Workplane: ...
    def val(self) -> Shape: ...
    def vals(self) -> Sequence[Shape]: ...
    def export(
        self,
        path: str,
        exportType: object | None = ...,
        opt: dict[str, object] | None = ...,
        tolerance: float = ...,
        angularTolerance: float = ...,
    ) -> None: ...

class Color:
    def __init__(
        self, name: str | float, green: float | None = ..., blue: float | None = ...
    ) -> None: ...

class Assembly:
    name: str
    def __init__(self, obj: object | None = ..., name: str | None = ...) -> None: ...
    def add(
        self, obj: object, name: str | None = ..., color: Color | None = ...
    ) -> None: ...
    def export(
        self, path: str, exportType: object | None = ..., **kwargs: object
    ) -> None: ...
    @classmethod
    def load(cls, path: str) -> Assembly: ...

class ExportTypes:
    STEP: object

class _Importers:
    def importStep(self, path: str) -> Workplane: ...

class _Exporters:
    ExportTypes: type[ExportTypes]

importers: _Importers
exporters: _Exporters
